CREATE TABLE brand (
    brandId INT4 UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(256) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE model (
    modelId INT4 UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(256) NOT NULL,
    brandId INT4 UNSIGNED NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (brandId)
        REFERENCES brand(brandId)
);

CREATE TABLE feature (
    featureId INT4 UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(256) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user (
    userId INT4 UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL,
    name VARCHAR(64) NOT NULL,
    surname VARCHAR(64) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    role ENUM('USER', 'ADMIN') default 'USER',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE car (
    carId INT4 UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    userId INT4 UNSIGNED NOT NULL,
    year VARCHAR(4) NOT NULL,
    price VARCHAR(16) NOT NULL,
    modelId INT4 UNSIGNED NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId)
        REFERENCES user (userId),
    FOREIGN KEY (modelId)
        REFERENCES model (modelId)
);

CREATE TABLE image (
    imageId INT4 UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    carId INT4 UNSIGNED NOT NULL,
    src VARCHAR(512) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (carId)
        REFERENCES car (carId)
);

CREATE TABLE carFeature (
    carId INT4 UNSIGNED NOT NULL,
    featureId INT4 UNSIGNED NOT NULL,
    FOREIGN KEY (carId)
        REFERENCES car (carId),
    FOREIGN KEY (featureId)
        REFERENCES feature (featureId),
    PRIMARY KEY (carId , featureId)
);